.\" xnelson
.\" Author: William Woodruff (woodruffw)
.TH xnelson 1 "12 March 2015" "1.0" "User Commands"
.SH NAME
.BR xnelson " - Nelson, on X"
.SH SYNOPSIS
.B xnelson
.PP
.B xnelson
takes no arguments. You shouldn't argue with a professor.
.SH DESCRIPTION
.B xnelson
can do the following things:
.IP *
make you crave coffee
.IP *
take up space on your hard drive
.IP *
make you submit your projects on time
.IP *
remind you how much you dislike C
.PP
.B xnelson
CANNOT do the following things:
.IP *
stop your programs from segfaulting
.IP *
make your programs work on
.I both
the submit server and Grace at the same time
.IP *
give you an A in CMSC216
.PP
If you discover any other things
.B xnelson
can or cannot do, please tell me.
.SH ENVIRONMENT
.BR DISPLAY " - Must be set properly in order to connect to X."
.SH INSECTOS
If
.B xnelson
is left open long enough, you can hear it whisper undefined behavior to you.
.SH AUTHOR
.B xnelson
was written by William Woodruff and can be found in the public domain at
.I https://github.com/woodruffw/xnelson
.SH SEE ALSO
.BR xeyes (1)
